# Generated by Django 3.0.3 on 2022-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
