# Generated by Django 3.0.3 on 2022-10-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subject',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
